# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:

- script:'ls -l gradlew'
  displayName: 'Run a one-line script'

- task: Gradle@2
  inputs:
    workingDirectory: '$(system.defaultWorkingDirectory)/MyApp'
    gradleWrapperFile: '$(system.defaultWorkingDirectory)gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
  displayName: gradlew assembleDebug test



- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
