# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'macOS-latest'

steps:

- script: |
    brew tap homebrew/cask-versions
    brew install --scask adoptopenjdk8
    brew install android-sdk
    export Android_HOME=/us/r/local/share/android-sdk
    export PATH=$ANDRIOD_HOME/tools:$PATH
    export PATH=$ANDRIOD_HOME/platform-tools:$PATH
    yes | sdkmanager --licenses
    sdkmanager "platform;android-23"
  displayName: 'Set an ADR EnV'

- task: Gradle@2
  inputs:
    workingDirectory: ''
    gradleWrapperFile: 'gradlew'
    gradleOptions: '-Xmx3072m'
    javaHomeOption: 'JDKVersion'
    jdkVersionOption: '1.8'
    jdkArchitectureOption: 'x64'
    publishJUnitResults: false
    testResultsFiles: '**/TEST-*.xml'
  displayName: gradlew assembleDebug test

- script: 'ls -l gradlew'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
